name: Telegram Messenger
on:
  schedule:
    - cron: '30 10 24 5 *' # DYNAMIC_SCHEDULE (Scheduler will overwrite this)
  workflow_dispatch:

jobs:
  send-alert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run Telegram Script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python Messenger.py

  reschedule:
    needs: send-alert
    permissions:
      contents: write
    uses: ./.github/workflows/scheduler.yml
    secrets:
      WORKFLOW_PUSH_TOKEN: ${{ secrets.WORKFLOW_PUSH_TOKEN }}
